# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: feedback

# Model Form Field configuration
form: $/idesigning/feedback/models/feedback/fields.yaml

# Model Class name
modelClass: IDesigning\Feedback\Models\Feedback

# Default redirect location
defaultRedirect: idesigning/feedback/feedbacks

# Create page
create:
    title: Добавить запись
    redirect: idesigning/feedback/feedbacks/update/:id
    redirectClose: idesigning/feedback/feedbacks

# Update page
update:
    title: Редактировать запись
    redirect: idesigning/feedback/feedbacks
    redirectClose: idesigning/feedback/feedbacks

# Preview page
preview:
    title: Предпросмотр