# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: channel

# Model Form Field configuration
form: $/idesigning/feedback/models/channel/fields.yaml

# Model Class name
modelClass: IDesigning\Feedback\Models\Channel

# Default redirect location
defaultRedirect: idesigning/feedback/channels

# Create page
create:
    title: Добавить канал
    redirect: idesigning/feedback/channels/update/:id
    redirectClose: idesigning/feedback/channels

# Update page
update:
    title: Редактировать канал
    redirect: idesigning/feedback/channels
    redirectClose: idesigning/feedback/channels

# Preview page
preview:
    title: Предпросмотр канала